# Використовуємо базовий образ Nginx
FROM nginx

# Копіюємо ваш index.html до каталогу, що відповідає за веб-сторінки Nginx
COPY index.html /usr/share/nginx/html

# Вказуємо порт, на якому буде працювати сервер Nginx
EXPOSE 80

